name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  sanity:
    name: Sanity
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Install Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.11'

    - name: Run pre-commit checks
      uses: pre-commit/action@v3.0.1
